/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccessLogRouteImport } from './routes/_authenticated/access-log'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedClinicianRouteImport } from './routes/_authenticated/clinician'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthenticatedCooperativeRouteImport } from './routes/_authenticated/cooperative'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDetectionRouteImport } from './routes/_authenticated/detection'
import { Route as AuthenticatedFacilityRouteImport } from './routes/_authenticated/facility'
import { Route as AuthenticatedInsurerRouteImport } from './routes/_authenticated/insurer'
import { Route as AuthenticatedInteropRouteImport } from './routes/_authenticated/interop'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPreventionRouteImport } from './routes/_authenticated/prevention'
import { Route as AuthenticatedRecordRouteImport } from './routes/_authenticated/record'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated/registry'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients_.$patientId'
import { Route as ApiPublicFhirMetadataRouteImport } from './routes/api/public/fhir/metadata'
import { Route as ApiPublicFhirObservationRouteImport } from './routes/api/public/fhir/observation'
import { Route as ApiPublicFhirPatientIdRouteImport } from './routes/api/public/fhir/patient.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessLogRoute = AuthenticatedAccessLogRouteImport.update({
  id: '/access-log',
  path: '/access-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicianRoute = AuthenticatedClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCooperativeRoute =
  AuthenticatedCooperativeRouteImport.update({
    id: '/cooperative',
    path: '/cooperative',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDetectionRoute = AuthenticatedDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilityRoute = AuthenticatedFacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsurerRoute = AuthenticatedInsurerRouteImport.update({
  id: '/insurer',
  path: '/insurer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteropRoute = AuthenticatedInteropRouteImport.update({
  id: '/interop',
  path: '/interop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreventionRoute = AuthenticatedPreventionRouteImport.update({
  id: '/prevention',
  path: '/prevention',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordRoute = AuthenticatedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients_/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFhirMetadataRoute = ApiPublicFhirMetadataRouteImport.update({
  id: '/api/public/fhir/metadata',
  path: '/api/public/fhir/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFhirObservationRoute =
  ApiPublicFhirObservationRouteImport.update({
    id: '/api/public/fhir/observation',
    path: '/api/public/fhir/observation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFhirPatientIdRoute = ApiPublicFhirPatientIdRouteImport.update({
  id: '/api/public/fhir/patient/$id',
  path: '/api/public/fhir/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/access-log': typeof AuthenticatedAccessLogRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/clinician': typeof AuthenticatedClinicianRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/cooperative': typeof AuthenticatedCooperativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/detection': typeof AuthenticatedDetectionRoute
  '/facility': typeof AuthenticatedFacilityRoute
  '/insurer': typeof AuthenticatedInsurerRoute
  '/interop': typeof AuthenticatedInteropRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/prevention': typeof AuthenticatedPreventionRoute
  '/record': typeof AuthenticatedRecordRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/api/public/fhir/metadata': typeof ApiPublicFhirMetadataRoute
  '/api/public/fhir/observation': typeof ApiPublicFhirObservationRoute
  '/api/public/fhir/patient/$id': typeof ApiPublicFhirPatientIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/access-log': typeof AuthenticatedAccessLogRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/clinician': typeof AuthenticatedClinicianRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/cooperative': typeof AuthenticatedCooperativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/detection': typeof AuthenticatedDetectionRoute
  '/facility': typeof AuthenticatedFacilityRoute
  '/insurer': typeof AuthenticatedInsurerRoute
  '/interop': typeof AuthenticatedInteropRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/prevention': typeof AuthenticatedPreventionRoute
  '/record': typeof AuthenticatedRecordRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/api/public/fhir/metadata': typeof ApiPublicFhirMetadataRoute
  '/api/public/fhir/observation': typeof ApiPublicFhirObservationRoute
  '/api/public/fhir/patient/$id': typeof ApiPublicFhirPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/access-log': typeof AuthenticatedAccessLogRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/clinician': typeof AuthenticatedClinicianRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/cooperative': typeof AuthenticatedCooperativeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/detection': typeof AuthenticatedDetectionRoute
  '/_authenticated/facility': typeof AuthenticatedFacilityRoute
  '/_authenticated/insurer': typeof AuthenticatedInsurerRoute
  '/_authenticated/interop': typeof AuthenticatedInteropRoute
  '/_authenticated/patient': typeof AuthenticatedPatientRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/prevention': typeof AuthenticatedPreventionRoute
  '/_authenticated/record': typeof AuthenticatedRecordRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/patients_/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/api/public/fhir/metadata': typeof ApiPublicFhirMetadataRoute
  '/api/public/fhir/observation': typeof ApiPublicFhirObservationRoute
  '/api/public/fhir/patient/$id': typeof ApiPublicFhirPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/access-log'
    | '/appointments'
    | '/clinician'
    | '/consent'
    | '/cooperative'
    | '/dashboard'
    | '/detection'
    | '/facility'
    | '/insurer'
    | '/interop'
    | '/patient'
    | '/patients'
    | '/prevention'
    | '/record'
    | '/registry'
    | '/settings'
    | '/patients/$patientId'
    | '/api/public/fhir/metadata'
    | '/api/public/fhir/observation'
    | '/api/public/fhir/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/access-log'
    | '/appointments'
    | '/clinician'
    | '/consent'
    | '/cooperative'
    | '/dashboard'
    | '/detection'
    | '/facility'
    | '/insurer'
    | '/interop'
    | '/patient'
    | '/patients'
    | '/prevention'
    | '/record'
    | '/registry'
    | '/settings'
    | '/'
    | '/patients/$patientId'
    | '/api/public/fhir/metadata'
    | '/api/public/fhir/observation'
    | '/api/public/fhir/patient/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/access-log'
    | '/_authenticated/appointments'
    | '/_authenticated/clinician'
    | '/_authenticated/consent'
    | '/_authenticated/cooperative'
    | '/_authenticated/dashboard'
    | '/_authenticated/detection'
    | '/_authenticated/facility'
    | '/_authenticated/insurer'
    | '/_authenticated/interop'
    | '/_authenticated/patient'
    | '/_authenticated/patients'
    | '/_authenticated/prevention'
    | '/_authenticated/record'
    | '/_authenticated/registry'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/patients_/$patientId'
    | '/api/public/fhir/metadata'
    | '/api/public/fhir/observation'
    | '/api/public/fhir/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicFhirMetadataRoute: typeof ApiPublicFhirMetadataRoute
  ApiPublicFhirObservationRoute: typeof ApiPublicFhirObservationRoute
  ApiPublicFhirPatientIdRoute: typeof ApiPublicFhirPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-log': {
      id: '/_authenticated/access-log'
      path: '/access-log'
      fullPath: '/access-log'
      preLoaderRoute: typeof AuthenticatedAccessLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinician': {
      id: '/_authenticated/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof AuthenticatedClinicianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cooperative': {
      id: '/_authenticated/cooperative'
      path: '/cooperative'
      fullPath: '/cooperative'
      preLoaderRoute: typeof AuthenticatedCooperativeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/detection': {
      id: '/_authenticated/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof AuthenticatedDetectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility': {
      id: '/_authenticated/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof AuthenticatedFacilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurer': {
      id: '/_authenticated/insurer'
      path: '/insurer'
      fullPath: '/insurer'
      preLoaderRoute: typeof AuthenticatedInsurerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interop': {
      id: '/_authenticated/interop'
      path: '/interop'
      fullPath: '/interop'
      preLoaderRoute: typeof AuthenticatedInteropRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prevention': {
      id: '/_authenticated/prevention'
      path: '/prevention'
      fullPath: '/prevention'
      preLoaderRoute: typeof AuthenticatedPreventionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/record': {
      id: '/_authenticated/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthenticatedRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients_/$patientId': {
      id: '/_authenticated/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fhir/metadata': {
      id: '/api/public/fhir/metadata'
      path: '/api/public/fhir/metadata'
      fullPath: '/api/public/fhir/metadata'
      preLoaderRoute: typeof ApiPublicFhirMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fhir/observation': {
      id: '/api/public/fhir/observation'
      path: '/api/public/fhir/observation'
      fullPath: '/api/public/fhir/observation'
      preLoaderRoute: typeof ApiPublicFhirObservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fhir/patient/$id': {
      id: '/api/public/fhir/patient/$id'
      path: '/api/public/fhir/patient/$id'
      fullPath: '/api/public/fhir/patient/$id'
      preLoaderRoute: typeof ApiPublicFhirPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessLogRoute: typeof AuthenticatedAccessLogRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedClinicianRoute: typeof AuthenticatedClinicianRoute
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedCooperativeRoute: typeof AuthenticatedCooperativeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDetectionRoute: typeof AuthenticatedDetectionRoute
  AuthenticatedFacilityRoute: typeof AuthenticatedFacilityRoute
  AuthenticatedInsurerRoute: typeof AuthenticatedInsurerRoute
  AuthenticatedInteropRoute: typeof AuthenticatedInteropRoute
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPreventionRoute: typeof AuthenticatedPreventionRoute
  AuthenticatedRecordRoute: typeof AuthenticatedRecordRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessLogRoute: AuthenticatedAccessLogRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedClinicianRoute: AuthenticatedClinicianRoute,
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedCooperativeRoute: AuthenticatedCooperativeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDetectionRoute: AuthenticatedDetectionRoute,
  AuthenticatedFacilityRoute: AuthenticatedFacilityRoute,
  AuthenticatedInsurerRoute: AuthenticatedInsurerRoute,
  AuthenticatedInteropRoute: AuthenticatedInteropRoute,
  AuthenticatedPatientRoute: AuthenticatedPatientRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPreventionRoute: AuthenticatedPreventionRoute,
  AuthenticatedRecordRoute: AuthenticatedRecordRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicFhirMetadataRoute: ApiPublicFhirMetadataRoute,
  ApiPublicFhirObservationRoute: ApiPublicFhirObservationRoute,
  ApiPublicFhirPatientIdRoute: ApiPublicFhirPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
